FROM node:20.5.0

# ALlows the user to define a default port to populate the UI.
# Pass a desired value in your docker run/compose environment
ARG DEFAULT_PORT
ENV DEFAULT_PORT=$DEFAULT_PORT

COPY web/package.json ./
RUN yarn install
COPY ./web ./web
WORKDIR /web
EXPOSE 8080
CMD ["yarn", "dev"]
