---
version: "3.8"
services:
  web:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    container_name: web
    environment:
      - DEFAULT_PORT=443
      - GOOGLE_ANALYTICS=  # optional
    ports:
      - 8080:8080
  api:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: api
    environment:
      - ALLOW_PRIVATE=false
    ports:
      - 8000:8000
