FROM node:alpine

# ALlows the user to define a default port to populate the UI.
# Pass a desired value in your docker run/compose environment
ARG DEFAULT_PORT
ENV DEFAULT_PORT=$DEFAULT_PORT

COPY webui/package.json webui/yarn.lock ./
RUN yarn install && yarn global add webpack
COPY ./webui ./app
WORKDIR /app
CMD ["yarn", "start"]
