---
version: "3.8"
services:
  portchecker:
    image: ghcr.io/dsgnr/portcheckerio:latest
    pull_policy: always
    container_name: portcheckerio
    environment:
      - API_URL=
      - DEFAULT_PORT=
    ports:
      - 80:80
    restart: unless-stopped
