[tool.black]
line-length = 100
target-version = ["py36"]
skip-string-normalization = true
skip-numeric-underscore-normalization = true

[tool.isort]
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true
multi_line_output = 3
use_parentheses = true
line_length = 100
wrap_length = 100
ensure_newline_before_comments = true

import_heading_firstparty = "First Party"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third Party"
