[tool.poetry]
package-mode = false
name = "portchecker.io"
version = "2.0.0"
description = """portchecker.io is an open-source API for checking port \
    availability on specified hostnames or IP addresses. \
    Ideal for developers and network admins, it helps troubleshoot network \
    setups, validate firewall rules, and assess potential access points."""
authors = ["dsgnr <email@danielhand.io>"]
repository = "https://github.com/dsgnr/portchecker.io"
license = "GNU General Public License v3.0"
readme = "../README.md"

[tool.poetry.dependencies]
python = "^3.12"
litestar = "2.12.1"
gunicorn = "23.0.0"
pydantic = "2.9.2"
uvicorn = {extras = ["standard"], version = "0.32.0"}
tomli = "^2.0.2"

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.1"
isort = "^5.13.2"
pytest = "^8.3.3"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
atomic = true
profile = "black"
line_length = 88
known_first_party = ["app"]

[tool.pylint]
init-hook='import sys; sys.path.append("api")'

[tool.pytest.ini_options]
pythonpath = [
  "api"
]
