[tool.poetry]
name = "portchecker-api"
version = "2.0.0"
description = "A simple API to query ports for hostnames or IP addresses"
authors = ["dsgnr <email@danielhand.io>"]
license = "GNU General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
litestar = "2.12.1"
gunicorn = "23.0.0"
pydantic = "2.9.2"
uvicorn = {extras = ["standard"], version = "0.32.0"}

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.1"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
atomic = true
profile = "black"
line_length = 88
known_first_party = ["app"]

[tool.pylint]
init-hook='import sys; sys.path.append("api")'
