[tool.poetry]
package-mode = false
name = "portchecker.io"
version = "3.2.2"
description = """portchecker.io is an open-source API for checking port \
    availability on specified hostnames or IP addresses. \
    Ideal for developers and network admins, it helps troubleshoot network \
    setups, validate firewall rules, and assess potential access points."""
authors = ["dsgnr <email@danielhand.io>"]
repository = "https://github.com/dsgnr/portchecker.io"
license = "GNU General Public License v3.0"
readme = "../README.md"

[tool.poetry.dependencies]
python = "^3.12"
litestar = {extras = ["prometheus"], version = "^2.15.2"}
httpcore = "^1.0.9"
gunicorn = "23.0.0"
pydantic = "^2.11.3"
uvicorn = {extras = ["standard"], version = "^0.34.2"}
tomli = "^2.2.1"

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.6"
isort = "^6.0.1"
pytest = "^8.3.4"
pytest-mock = "^3.14.0"
pytest-cov = "^6.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
atomic = true
profile = "black"
line_length = 88
known_first_party = ["app"]

[tool.pylint]
init-hook='import sys; sys.path.append("api")'

[tool.pytest.ini_options]
pythonpath = [
  "api"
]
