{
 "title": "portchecker.io",
 "description": "Basic API Prometheus monitoring for portchecker.io",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Average Requests/Second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(portchecker_requests_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (portchecker_requests_total)",
     "legendFormat": "HTTP Status: {{status_code}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "portchecker_request_duration_seconds_sum{status_code=\"200\"}/portchecker_request_duration_seconds_count{status_code=\"200\"}\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(portchecker_requests_total{status_code=~\"2.*\"}) by(path, method) / sum(portchecker_requests_total{}) by(path, method)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "Percent of 4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(portchecker_requests_total{status_code=~\"4.*\"}) by(path, method) / sum(portchecker_requests_total{}) by(path, method)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(portchecker_requests_total{status_code=~\"5.*\"}) by(path, method) / sum(portchecker_requests_total{}) by(path, method)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(portchecker_request_duration_seconds_count{}[1m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "portchecker_request_duration_seconds_sum{} / portchecker_request_duration_seconds_count{}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "description": "Resets to 0 when app rolls out/restarts",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(path) (portchecker_request_duration_seconds_count)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}