---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.rabbitmq.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  enabled_plugins: |
    [rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    default_vhost = {{ .Values.rabbitmq_vhost }}
    default_user = {{ .Values.rabbitmq_user }}
    default_pass = {{ .Values.rabbitmq_pass }}
    loopback_users.guest = false
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.only_log_warning = true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.rabbitmq.name }}-env
  namespace: {{ .Release.Namespace }}
data:
  RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit consumer_timeout false"
  RABBITMQ_HA_POLICY: '{\"ha-mode\":\"all\"}'
