---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.service.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.rabbitmq.name }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.service.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
    - events
  verbs:
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.service.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.rabbitmq.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Namespace }}-{{ .Values.service.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.service.rabbitmq.name }}
