---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.api.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.api.name }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.api.port }}
  selector:
    app: {{ .Values.service.api.name }}
