name: API

on:
  pull_request:
    paths:
      - backend/**

defaults:
  run:
    working-directory: backend

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Valiate poetry.lock
        run: poetry check

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Test with pytest
        run: coverage run -m pytest tests

      - name: Generate Coverage Report
        run: coverage report
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Valiate poetry.lock
        run: poetry check

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Test
        run: pylint api tests
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Valiate poetry.lock
        run: poetry check

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Test
        run: isort api tests --check-only
